<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const VERSIONS = array (
  'doctrine/annotations' => 'v1.4.0@54cacc9b81758b14e3ce750f205a393d52339e97',
  'doctrine/cache' => 'v1.6.2@eb152c5100571c7a45470ff2a35095ab3f3b900b',
  'doctrine/collections' => 'v1.4.0@1a4fb7e902202c33cce8c55989b945612943c2ba',
  'doctrine/common' => 'v2.7.3@4acb8f89626baafede6ee5475bc5844096eba8a9',
  'doctrine/dbal' => 'v2.5.13@729340d8d1eec8f01bff708e12e449a3415af873',
  'doctrine/inflector' => 'v1.2.0@e11d84c6e018beedd929cff5220969a3c6d1d462',
  'doctrine/instantiator' => '1.0.5@8e884e78f9f0eb1329e445619e04456e64d8051d',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.3.1@fda27fc96d20a1abd46d4526387c7d6d416da263',
  'doctrine/orm' => 'v2.5.13@93103f44a3e36e7b48165b6e6b736833f33b18ef',
  'neos/cache' => '4.2.6@cbf09dcb2317e10ee7679a24a9dbbe1d3c4f421f',
  'neos/composer-plugin' => '2.0.1@cd20e3c9b548127f4fa1e0f31662072bf82250d4',
  'neos/eel' => '4.2.6@4b560851677f30fb2a4ffedf7a663ddb36e57293',
  'neos/error-messages' => '4.2.6@5151ea905882f6e41997ba296506ff5e52e4a86a',
  'neos/flow' => '4.2.6@6ec6c17df4f6dd7722ac1187d2739447cfe1c5e4',
  'neos/fluid-adaptor' => '4.2.6@8be532a5a1aad696026c3b140d20108f199823e9',
  'neos/utility-arrays' => '4.2.6@392de8e12f9329881a54fe6fdb85d5489fe8a9e8',
  'neos/utility-files' => '4.2.6@df2605665fb5fc40b9016cf84be140d0b78edb64',
  'neos/utility-lock' => '4.2.6@4ac0ac55bf34cac7dd83044b0a259b7aa2100fb6',
  'neos/utility-mediatypes' => '4.2.6@4369e98cef651bf4a972a927c539be9b8231a31c',
  'neos/utility-objecthandling' => '4.2.6@beb1f4ff8d5c6d9e715dc3051b813412f1ce3796',
  'neos/utility-opcodecache' => '4.2.6@ad6343bc86d64d9344a78e13d507c8d8cdc8daf6',
  'neos/utility-pdo' => '4.2.6@0e02f584f78cf45093e3dbdd6195ecdd35ac9a73',
  'neos/utility-schema' => '4.2.6@fbf6010f55a34f12de689bcbfee1e4eba28c166b',
  'neos/utility-unicode' => '4.2.6@1035d44520e50147bec17e103f1e2acb95917116',
  'neos/welcome' => '4.2.0@33137b99e1e5329fd7d1a6696a154a62b560e0da',
  'ocramius/package-versions' => '1.2.0@ad8a245decad4897cc6b432743913dad0d69753c',
  'ocramius/proxy-manager' => '2.0.4@a55d08229f4f614bf335759ed0cf63378feeb2e6',
  'paragonie/random_compat' => 'v2.0.11@5da4d3c796c275c55f057af5a643ae297d96b4d8',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'ramsey/uuid' => '3.7.1@45cffe822057a09e05f7bd09ec5fb88eeecd2334',
  'symfony/console' => 'v2.8.32@46270f1ca44f08ebc134ce120fd2c2baf5fd63de',
  'symfony/debug' => 'v3.0.9@697c527acd9ea1b2d3efac34d9806bf255278b0a',
  'symfony/dom-crawler' => 'v2.8.32@eeb78092b5cc95b9e37017887da0e39f1530b8a8',
  'symfony/polyfill-mbstring' => 'v1.6.0@2ec8b39c38cb16674bbf3fea2b6ce5bf117e1296',
  'symfony/yaml' => 'v2.8.32@968ef42161e4bc04200119da473077f9e7015128',
  'typo3fluid/fluid' => '2.1.3@52ccc0a1d4f1039b95a289dc44b2f6885a463799',
  'zendframework/zend-code' => '3.1.0@2899c17f83a7207f2d7f53ec2f421204d3beea27',
  'zendframework/zend-eventmanager' => '3.2.0@9d72db10ceb6e42fb92350c0cb54460da61bd79c',
  'mikey179/vfsStream' => 'v1.6.5@d5fec95f541d4d71c4823bb5e30cf9b9e5b96145',
  'myclabs/deep-copy' => '1.7.0@3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e',
  'neos/behat' => 'dev-master@5a2f49699b5cfcdb300f4d93988bf2f0b7a445cc',
  'neos/buildessentials' => '4.2.0@d39de9e0ed99c31bf1407d000d6233aba9580082',
  'neos/kickstarter' => '4.2.6@4adaba199eeb5fc442659c9b5e165331712275c5',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.2.0@66465776cfc249844bde6d117abff1d22e06c2da',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => '1.7.3@e4ed002c67da8eceb0eb8ddb8b3847bb53c5c2bf',
  'phpunit/php-code-coverage' => '5.2.0@e648abfd8ffb1d54ad549b027b75e376e9055d02',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '2.0.2@791198a2c6254db10131eecfe8c06670700904db',
  'phpunit/phpunit' => '6.0.13@df38633f62b45fbb9612275274b4553c34a863b2',
  'phpunit/phpunit-mock-objects' => '4.0.4@2f789b59ab89669015ad984afa350c4ec577ade0',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '2.0.0@20f84f468cb67efee293246e6a09619b891f55f0',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '2.0.0@5795ffe5dc5b02460c3e34222fee8cbe245d8fac',
  'sebastian/exporter' => '3.1.0@234199f4528de6d12aaa58b612e98f7d36adb937',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5',
  'sebastian/object-reflector' => '1.1.1@773f97c67f28de00d397be301821b06708fca0be',
  'sebastian/recursion-context' => '3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'theseer/tokenizer' => '1.1.0@cb2f008f3f05af2893a87208fe6a6c4985483f8b',
  'webmozart/assert' => '1.2.0@2db61e59ff05fe5126d152bd0655c9ea113e550f',
  'neos/flow-base-distribution' => '4.2.6@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (! isset(self::VERSIONS[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return self::VERSIONS[$packageName];
    }
}
