version: '2'
services:
  trello_api:
    build: ""
    container_name: 'trello_api'
    ports:
     - "1000:80"
    volumes:
     - ..:/var/www/trello
  trello_db:
    image: mysql:5.7
    container_name: 'trello_db'
    ports:
      - "3001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senhaforte
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "2000:80"
    depends_on:
      - trello_db
    links:
      - "trello_db:db"