version: '2'
services:
  trello_api:
    build: ""
    container_name: 'trello_api'
    ports:
     - "3000:80"
    volumes:
     - ..:/var/www/trello
  db:
    image: mysql:latest
    container_name: 'db'
    ports:
      - "3001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senhaforte
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "2000:80"
    depends_on:
      - db
    links:
      - "db:db"