<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const VERSIONS = array (
  'behat/transliterator' => 'v1.2.0@826ce7e9c2a6664c0d1f381cbb38b1fb80a7ee2c',
  'doctrine/annotations' => 'v1.4.0@54cacc9b81758b14e3ce750f205a393d52339e97',
  'doctrine/cache' => 'v1.6.2@eb152c5100571c7a45470ff2a35095ab3f3b900b',
  'doctrine/collections' => 'v1.4.0@1a4fb7e902202c33cce8c55989b945612943c2ba',
  'doctrine/common' => 'v2.7.3@4acb8f89626baafede6ee5475bc5844096eba8a9',
  'doctrine/dbal' => 'v2.5.13@729340d8d1eec8f01bff708e12e449a3415af873',
  'doctrine/inflector' => 'v1.2.0@e11d84c6e018beedd929cff5220969a3c6d1d462',
  'doctrine/instantiator' => '1.0.5@8e884e78f9f0eb1329e445619e04456e64d8051d',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.3.1@fda27fc96d20a1abd46d4526387c7d6d416da263',
  'doctrine/orm' => 'v2.5.14@810a7baf81462a5ddf10e8baa8cb94b6eec02754',
  'gedmo/doctrine-extensions' => 'v2.4.35@1e400fbd05b7e5f912f55fe95805450f7d3bed60',
  'guzzlehttp/guzzle' => '6.3.3@407b0cb880ace85c9b63c5f9551db498cb2d50ba',
  'guzzlehttp/promises' => 'v1.3.1@a59da6cf61d80060647ff4d3eb2c03a2bc694646',
  'guzzlehttp/psr7' => '1.4.2@f5b8a8512e2b58b0071a7280e39f14f72e05d87c',
  'neos/cache' => '4.2.10@9e415b5e6493c4c5f7c2838fcd2dd5a48f1cfa87',
  'neos/composer-plugin' => '2.0.1@cd20e3c9b548127f4fa1e0f31662072bf82250d4',
  'neos/eel' => '4.2.10@4b560851677f30fb2a4ffedf7a663ddb36e57293',
  'neos/error-messages' => '4.2.10@5151ea905882f6e41997ba296506ff5e52e4a86a',
  'neos/flow' => '4.2.10@c3825eddc5e8b53daec34840212837d128632b84',
  'neos/fluid-adaptor' => '4.2.10@1f951f44eb9c8dda9a3b6f9eacf1c76f8a23c5a9',
  'neos/utility-arrays' => '4.2.10@5d7a1a1745ea121e50252bab95add89400b28acc',
  'neos/utility-files' => '4.2.10@df2605665fb5fc40b9016cf84be140d0b78edb64',
  'neos/utility-lock' => '4.2.10@0e9029d878a6564f8d5db3460fc1ca56cbaae122',
  'neos/utility-mediatypes' => '4.2.10@4369e98cef651bf4a972a927c539be9b8231a31c',
  'neos/utility-objecthandling' => '4.2.10@beb1f4ff8d5c6d9e715dc3051b813412f1ce3796',
  'neos/utility-opcodecache' => '4.2.10@ad6343bc86d64d9344a78e13d507c8d8cdc8daf6',
  'neos/utility-pdo' => '4.2.10@0e02f584f78cf45093e3dbdd6195ecdd35ac9a73',
  'neos/utility-schema' => '4.2.10@fbf6010f55a34f12de689bcbfee1e4eba28c166b',
  'neos/utility-unicode' => '4.2.10@5422f00ef5d5d532d2391268c4caec81ebeb46af',
  'neos/welcome' => '4.2.0@33137b99e1e5329fd7d1a6696a154a62b560e0da',
  'ocramius/package-versions' => '1.2.0@ad8a245decad4897cc6b432743913dad0d69753c',
  'ocramius/proxy-manager' => '2.0.4@a55d08229f4f614bf335759ed0cf63378feeb2e6',
  'paragonie/random_compat' => 'v2.0.12@258c89a6b97de7dfaf5b8c7607d0478e236b04fb',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'ramsey/uuid' => '3.7.3@44abcdad877d9a46685a3a4d221e3b2c4b87cb76',
  'symfony/console' => 'v2.8.39@932d1e4f7f33ee37d3534f5f452474daa66283c2',
  'symfony/debug' => 'v3.0.9@697c527acd9ea1b2d3efac34d9806bf255278b0a',
  'symfony/dom-crawler' => 'v2.8.39@a7a21660f1b25a1feeadee32fc4cf62d13329c91',
  'symfony/polyfill-mbstring' => 'v1.8.0@3296adf6a6454a050679cde90f95350ad604b171',
  'symfony/yaml' => 'v2.8.39@d20bd2bdee063863e426297af41eda45ccad6f7e',
  'typo3fluid/fluid' => '2.1.3@52ccc0a1d4f1039b95a289dc44b2f6885a463799',
  'webonyx/graphql-php' => 'v0.9.14@ed6629130869893e6efb5757dab5812def357bce',
  'wwwision/graphql' => 'v2.1.0@5dbbcfcf941691a0e21441cebafbf549dd9395f0',
  'zendframework/zend-code' => '3.1.0@2899c17f83a7207f2d7f53ec2f421204d3beea27',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'mikey179/vfsStream' => 'v1.6.5@d5fec95f541d4d71c4823bb5e30cf9b9e5b96145',
  'myclabs/deep-copy' => '1.7.0@3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e',
  'neos/behat' => 'dev-master@0b7c4f6bb1dbfe4e7115770c0d7ca2a58be896bd',
  'neos/buildessentials' => '4.2.1@a87d5faee827e4898a5301d491996a2386783231',
  'neos/kickstarter' => '4.2.10@4adaba199eeb5fc442659c9b5e165331712275c5',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.0@94fd0001232e47129dd3504189fa1c7225010d08',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => '1.7.6@33a7e3c4fda54e912ff6338c48823bd5c0f0b712',
  'phpunit/php-code-coverage' => '5.2.0@e648abfd8ffb1d54ad549b027b75e376e9055d02',
  'phpunit/php-file-iterator' => '1.4.5@730b01bc3e867237eaac355e06a36b85dd93a8b4',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '2.0.2@791198a2c6254db10131eecfe8c06670700904db',
  'phpunit/phpunit' => '6.0.13@df38633f62b45fbb9612275274b4553c34a863b2',
  'phpunit/phpunit-mock-objects' => '4.0.4@2f789b59ab89669015ad984afa350c4ec577ade0',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '2.0.0@20f84f468cb67efee293246e6a09619b891f55f0',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '2.0.0@5795ffe5dc5b02460c3e34222fee8cbe245d8fac',
  'sebastian/exporter' => '3.1.0@234199f4528de6d12aaa58b612e98f7d36adb937',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.3@7cfd9e65d11ffb5af41198476395774d4c8a84c5',
  'sebastian/object-reflector' => '1.1.1@773f97c67f28de00d397be301821b06708fca0be',
  'sebastian/recursion-context' => '3.0.0@5b0cd723502bac3b006cbf3dbf7a1e3fcefe4fa8',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'theseer/tokenizer' => '1.1.0@cb2f008f3f05af2893a87208fe6a6c4985483f8b',
  'webmozart/assert' => '1.3.0@0df1908962e7a3071564e857d86874dad1ef204a',
  'neos/flow-base-distribution' => 'dev-master@c03b9f6ac16482b37018942e0cf31e8f593211f8',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (! isset(self::VERSIONS[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return self::VERSIONS[$packageName];
    }
}
