Neos:
  Flow:
    persistence:

      # It is good practice to not specify user name and password of the database
      # connection in this global Settings.yaml file. Rather specify them in the
      # settings of the respective context (Production / Development ...).
      backendOptions:
        host: 'trello_db'    # adjust to your database host
        dbname: 'trello'
        user: 'root'
        password: 'senhaforte'
      doctrine:
        eventListeners:
          -
            events: ['onFlush', 'loadClassMetadata', 'prePersist']
            listener: 'Gedmo\Timestampable\TimestampableListener'

    # The following lines register the Flow default routes
    # For productive use you should move this setting to the main package of this
    # application and/or create custom routes.

  # You might need to uncomment the following lines and specify
  # the location of the PHP binary manually.
#    core:
#      phpBinaryPathAndFilename: 'C:/path/to/php.exe'

